---
title: "World Population Prospects Stats (1950 - 2100)"
author: "IF36 - SEKIRO (Othmane BEKKAL, Nicolas RIGOLAT, Robin NADAL, Zakaria ZAROUAL)"
date: "UTT - P25"
output:
  pdf_document: default
  html_document: default
---

## Table des matières

> [Introduction](#section-1) <br> [I. Données](#section-2) <br> [II. Plan d'analyse](#section-3) <br> [III. Exploration](#section-4) <br>

<a id="section-1"></a>

# Introduction
&ensp;Nous avons choisi d’utiliser le jeu de données **“World Population Prospects”**, mis à disposition par l’**Organisation des Nations Unies** via leur site officiel : [https://population.un.org/wpp](https://population.un.org/wpp)

&ensp;Ce dataset est mis à jour tous les 2 ans environ, la version utilisée sera la dernière, celle de 2024. Plus précisément, ces documents sont édités et publiés par le **DAES** (DESA en anglais), le *Département des Affaires Économiques et Sociales* qui est un “secrétariat” (un organisme principal) de l’ONU qui produit et analyse des datasets afin de produire des rapports et aide les pays à prendre des décisions et à avoir des agendas de politiques au fait des enjeux sociétaux et économiques. Les rapports publics portent par exemple sur l’avancement des droits des femmes, de la jeunesse, des autochtones, mais aussi sur l’état et les objectifs futurs des forêts, des énergies renouvelables, de l’économie et donc aussi de la démographie.

&ensp;Ces données contiennent des projections démographiques standardisées pour l’ensemble des pays du monde, couvrant la période de **1950 à 2100**. Les données de 1950 à 2023 sont des données issues de recensement de 238 pays/régions non-autonomes. Ce dataset constitue donc une source fiable, riche, et particulièrement pertinente dans un contexte de réflexion sur l’évolution des sociétés.

<a id="section-2"></a>

# I. Données

Notre dataset est constitué de 15 fichiers CSV thématiques couvrant l'évolution démographique mondiale sous différentes facettes : population totale, fécondité, mortalité, migration, et bien d'autres. Il propose une exploration à travers quatre niveaux de granularité spatiale : mondial, régional, national, et urbain/rural. Les données sont également regroupées par tranches d'âge quinquennales, permettant une analyse fine de l'évolution au fil du temps.

De plus, trois scénarios prospectifs (bas, moyen, haut) ont été élaborés selon les politiques natalistes des États, projetant ainsi plusieurs futurs possibles pour l'humanité.  
Ce vaste ensemble contient **84 360 observations** réparties sur **42 variables**, offrant une base solide pour comprendre les dynamiques démographiques passées, présentes et futures.

Chaque localisation est identifiée de manière unique, facilitant l'agrégation, la comparaison et l'interprétation des différentes séries temporelles disponibles.

<details>
<summary><b><font size="+1">Description des variables du dataset</font></b></summary>

| Colonne         | Format      | Type de données | Description |
|-----------------|-----------|-----------------|-------------|
| **SortOrder**            | int      | Discrète | Ordre des lignes |
| **LocID**                | int      | Discrète | Identifiant unique de la localisation |
| **Notes**                | string (nullable) | Nominale | Informations additionnelles |
| **ISO3_code**            | string (nullable) | Nominale | Code pays en 2 lettres selon la norme ISO 3166-1 alpha-3 |
| **ISO2_code**            | string (nullable) | Nominale | Code pays en 2 lettres selon la norme ISO 3166-1 alpha-2 |
| **SDMX_code**            | string (nullable) | Nominale | Code SDMX pour la localisation |
| **LocTypeID**            | int      | Discrète | Type de la localisation |
| **LocTypeName**          | string   | Nominale | Nom du type de localisation |
| **ParentID**             | int (nullable) | Discrète | Identifiant du parent (si la localisation fait partie d'une région) |
| **Location**             | string   | Nominale | Nom de la région/localisation |
| **VarID**                | int      | Discrète | Identifiant de la variable |
| **Variant**              | string   | Nominale | Type de scénario démographique (ex. Medium) |
| **Time**                 | int      | Ordinale | Année |
| **TPopulation1Jan**      | float    | Continue | Population totale au 1er janvier |
| **TPopulation1July**     | float    | Continue | Population totale au 1er juillet |
| **TPopulationMale1July** | float    | Continue | Population masculine au 1er juillet |
| **TPopulationFemale1July** | float | Continue | Population féminine au 1er juillet |
| **PopDensity**           | float    | Continue | Densité de population (habitants/km²) |
| **PopSexRatio**          | float    | Continue | Ratio hommes/femmes |
| **MedianAgePop**         | float    | Continue | Âge médian de la population |
| **NatChange**           | float    | Continue | Changement naturel de la population |
| **NatChangeRT**         | float    | Continue | Taux de changement naturel |
| **PopChange**           | float    | Continue | Changement total de la population |
| **PopGrowthRate**       | float    | Continue | Taux de croissance démographique |
| **DoublingTime**        | float    | Continue | Temps de doublement de la population |
| **Births**              | float    | Continue | Nombre total de naissances |
| **Births1519**          | float    | Continue | Naissances chez les 15-19 ans |
| **CBR**                 | float    | Continue | Taux brut de natalité (pour 1000 habitants) |
| **TFR**                 | float    | Continue | Taux de fécondité total (nombre moyen d'enfants par femme) |
| **NRR**                 | float    | Continue | Taux net de reproduction |
| **MAC**                 | float    | Continue | Âge moyen de la maternité |
| **SRB**                 | float    | Continue | Ratio de masculinité à la naissance (nombre de garçons pour 100 filles) |
| **Deaths**              | float    | Continue | Nombre total de décès |
| **DeathsMale**          | float    | Continue | Nombre de décès masculins |
| **DeathsFemale**        | float    | Continue | Nombre de décès féminins |
| **CDR**                 | float    | Continue | Taux brut de mortalité (pour 1000 habitants) |
| **LEx**                 | float    | Continue | Espérance de vie à la naissance |
| **LExMale**             | float    | Continue | Espérance de vie des hommes |
| **LExFemale**           | float    | Continue | Espérance de vie des femmes |
| **LE15**                | float    | Continue | Espérance de vie à 15 ans |
| **LE15Male**            | float    | Continue | Espérance de vie des hommes à 15 ans |
| **LE15Female**          | float    | Continue | Espérance de vie des femmes à 15 ans |
| **LE65**                | float    | Continue | Espérance de vie à 65 ans |
| **LE65Male**            | float    | Continue | Espérance de vie des hommes à 65 ans |
| **LE65Female**          | float    | Continue | Espérance de vie des femmes à 65 ans |
| **LE80**                | float    | Continue | Espérance de vie à 80 ans |
| **LE80Male**            | float    | Continue | Espérance de vie des hommes à 80 ans |
| **LE80Female**          | float    | Continue | Espérance de vie des femmes à 80 ans |
| **InfantDeaths**        | float    | Continue | Nombre de décès infantiles |
| **IMR**                 | float    | Continue | Taux de mortalité infantile (pour 1000 naissances vivantes) |
| **LBsurvivingAge1**     | float    | Continue | Nombre d'enfants survivant jusqu'à 1 an |
| **Under5Deaths**        | float    | Continue | Nombre de décès avant 5 ans |
| **Q5**                  | float    | Continue | Probabilité de mourir avant 5 ans |
| **Q0040, Q0040Male, Q0040Female** | float | Continue | Probabilité de mourir entre 0 et 40 ans (total, hommes, femmes) |
| **Q0060, Q0060Male, Q0060Female** | float | Continue | Probabilité de mourir entre 0 et 60 ans (total, hommes, femmes) |
| **Q1550, Q1550Male, Q1550Female** | float | Continue | Probabilité de mourir entre 15 et 50 ans (total, hommes, femmes) |
| **Q1560, Q1560Male, Q1560Female** | float | Continue | Probabilité de mourir entre 15 et 60 ans (total, hommes, femmes) |
| **NetMigrations**       | float    | Continue | Migration nette (immigrants - émigrants) |
| **CNMR**               | float    | Continue | Taux net de migration (pour 1000 habitants) |

</details>

<a id="section-3"></a>

# II. Plan d'analyse

<a id="section-4"></a>

# III. Exploration

```{r import, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library("readxl")
Dem_1950-2023 <- read_excel("./data/Dem_1950-2023.xlsx")
```


## 1. Comment le taux de fécondité total (TFR) a-t-il évolué entre 1950 et 2023 dans les cinq continents ?

**Hypothèse initiale** : Nous supposons que le TFR a globalement diminué sur tous les continents depuis 1950 avec des disparités régionales marquées (ex : déclin plus rapide en Europe qu'en Afrique). Le taux de fécondité total est le nombre d'enfant vivant à la naissance par femme. On ne compte pas ici l'indice de survie des enfants. Nous respecterons la division en continent de l'Amérique en quatre entités (South America, Central America, the Caribbean, and Northern America) faite par l'ONU dans ce dataset.

### Visualisation
```
data <- Dem_1950_2023
data_clean <- data %>%
  rename_with(tolower) %>%
  rename(
    year = `...11`,
    continent = `...3`,
    tfr = `...27`
  ) %>%
  filter(!is.na(year), !is.na(continent), !is.na(tfr)) %>%
  mutate(
    year = as.integer(year),
    tfr = as.numeric(tfr)
  ) %>% filter(continent %in% c("Africa", "Asia", "Europe", "Northern America", "Caribbean", "Central America", "South America", "Oceania"))
ggplot(data_clean, aes(x = year, y = tfr, color = continent)) +
  geom_line(size = 1.2) +
  geom_hline(yintercept=2.05,
             color="black",
             size=1)+
  labs(title = "Évolution du taux de fécondité total (TFR) par continent",
       x = "Année",
       y = "Taux de fécondité total (TFR)",
       color = "Continent",
       caption="Le seuil de renouvellement générationel est représenté par la ligne horizontale noire") +
  theme_minimal() +
  scale_x_continuous(breaks = c(seq(1950,2020, by=5)))+
  scale_y_continuous(expand = c(0,0), limits = c(0,7.5), breaks = c(seq(0,8, by=1)))+
  theme(
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12),
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 14)
  )

```
### Interprétation du graphique

La baisse globale du TFR, passant de 4,7 en 1950 à 2,3 en 2023, dissimule des réalités hétérogènes en fonction du continent.

&emsp; En Afrique, le TFR a connu un déclin relatif mais inachevé, diminuant de 6,7 à 4,3 sur 73 ans. Cette transition lente peut s'expliquer par la persistance de normes pro-natalistes, par un accès limité à la contraception, la baisse faible de la mortalité infantile, divisée par quatre depuis 1950 qui n’a pas encore entraîné un ajustement proportionnel des comportements reproductifs (la seconde phase de la transition démographique).

&emsp; En Europe, le TFR a continuellement baissé dès les années 1970 pour atteindre 1,5 en 2023. L'Europe est sous le seuil de renouvellement depuis 1975, sans immigration la population aurait largement diminué.

&emsp;  On peut voir des données intéressantes des années 1950 à 1975. Si l'Amérique du Sud a une baisse continue et linéaire, l'Asie connaît des rebonds et de fortes baisses. En effet, l'année 1961, celle de la plus grande baisse, peut être corrélée avec la Grande famine chinoise (1959-1961). Mais sous cette moyenne se cache de grande disparité : dans six pays (Chine, Corée du Nord, Corée du Sud, Japon, Singapour, Thaïlande), la transition de la fécondité est largement achevée avec un nombre moyen d’enfants par femme qui est désormais inférieur au seuil de remplacement des génération. Le Japon, Singapour et la Corée du Sud se caractérisent même par des niveaux de fécondité parmi les plus bas au monde, inférieurs à 1,4 enfant par femme (faisant d’eux des ‘lowest-low’ fertility countries). La Chine, grâce à sa politique coercitive de l’enfant unique, a évité 400 millions de naissances, mais au prix d’un déséquilibre de genre historique. L’Inde, via des campagnes volontaristes comme "Us two, our two" (un couple, deux enfants), a réduit son TFR de 5,7 à 2,0.

&emsp; L’Océanie, avec un TFR moyen de 2,1, cache des fractures invisibles. L’Australie et la Nouvelle-Zélande (1,6) contrastent avec la Mélanésie, où la Papouasie-Nouvelle-Guinée maintient un TFR de 3,2. 

&emsp; Du côté des Amériques, deux schémas sont présents. L'Amérique du Nord (Northen America ou Amérique septentrionale) composé des États-Unis, du Canada ainsi que des Bermudes (Royaume-Uni), du  Groenland (Danemark) et de Saint-Pierre-et-Miquelon (France), suit une courbe très proche de celle de l'Europe. Le reste des Amériques; centrale, du sud et les Caraïbes ; suivent une trajectoire similaire à l'Asie avec une baisse qui les emmène tous en dessous du seuil de renouvellement.
